### ISSUE TITLE
While running the first test program I am getting below errors.

### ISSUE THREAD

**Issue by cthakar** [macopedia/Menta_MagentoSampleProject#1]
PHPUnit 3.7.38 by Sebastian Bergmann.

Could not find configuration key "testing.selenium.browser"

**Comment by tmotyl** [comment]
Hi @cthakar,
Thanks for your report!
Can you please check if adding this setting(testing.selenium.browser)  to the conf/default.xml 
Will fix the issue?

**Comment by cthakar** [comment]
It was not in conf/default.xml so I added as below 
<var name="testing.selenium.browser" value="crome"/>

As I have installed crome driver on my OS with debian

but Now getting below errors
Catchable fatal error: Argument 3 passed to Menta_SessionManager::init() must be an instance of array, string given in /home/menta/Menta_MagentoSampleProject/vendor/aoemedia/menta/lib/Menta/SessionManager.php on line 53

**Comment by afirlejczyk** [comment]
Hi @cthakar, 

I fixed some bugs in conf/default.xml.

Did you change value for setting **testing.selenium.capabilities** ? By default it is **'{}'** .

**Comment by cthakar** [comment]
HI @afirlejczyk 

Thank you so much for guiding. Yes I did change the value of testing.selenium.capabilities default {} to {firefox}.But Now I have reverted it back to default {}. and rerun the test and getting below error.
Fatal error: File not found: /home/menta/Menta_MagentoSampleProject/conf/../vendor/aoepeople/menta/lib/Menta/PHPUnit/Listener/HtmlResultPrinter.php in /home/menta/Menta_MagentoSampleProject/vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php on line 625

Thanks

**Comment by afirlejczyk** [comment]
@cthakar 
I fixed it in last commit 47867c015d3cf8e363c9f7406d9718aab63da939.
